// Version 2.0.0
// Supabase Realtime dependency is loaded by js/supabase.js.
import { supabase } from "./supabase.js";
import { CONFIG } from "./config.js";
import { toast } from "./auth.js";

const $ = (s) => document.querySelector(s);
let session = null, sessionPlayer = null, players = [], shared = {}, channel = null;
let currentRoom = "lobby", hidden = false, guardTimer = null, guardCountdownTimer = null;
let audioContext = null, ambientTimer = null;
const DEFAULT_SETTINGS = { difficulty:"normal", evidence:4, rooms:6, guards:1, guardWarning:5, guardCapture:4, music:true, sounds:true, masterVolume:.65 };
const ROOMS = { lobby:{name:"Main Lobby",cls:"room-lobby",map:[2,2],exits:{office:"West Office",security:"Security Hall",loading:"Front Exit"}},office:{name:"Records Office",cls:"room-office",map:[1,2],exits:{lobby:"Lobby",archive:"Archive"}},archive:{name:"Archive Stacks",cls:"room-archive",map:[0,2],exits:{office:"Office",evidence:"Evidence Room"}},security:{name:"Security Control",cls:"room-security",map:[2,1],exits:{lobby:"Lobby",evidence:"Service Corridor"}},evidence:{name:"Evidence Room",cls:"room-evidence",map:[1,1],exits:{archive:"Archive",security:"Security"}},loading:{name:"Loading Bay",cls:"room-loading",map:[2,0],exits:{lobby:"Lobby"}} };
const EVIDENCE = { keycard:["Archive keycard","A staff card marked A-17. Opens the archive terminal."],morse:["Decoded transmission","Morse message: LEDGER MOVED TO EVIDENCE 314."],photo:["Security photograph","A timestamped photograph showing the staged break-in team."],ledger:["Black ledger","The primary evidence. It must be carried out through the loading bay."] };
const HOTSPOTS = { office:{drawer:[36.5,51,29.5,15],radio:[72,18,15.5,35]},archive:{file:[77.5,17,12,9]},security:{monitor:[47.5,27,36,20]},evidence:{locker:[72,20,18,30]},loading:{exit:[68,22,25,58]} };
const LOCAL_SETTINGS_KEY = "nsd-settings-v2";
const NOTES_KEY = () => `nsd-notes-${window.currentProfile?.id||"guest"}`;
function esc(v=""){const d=document.createElement("div");d.textContent=v;return d.innerHTML;}
function randomCode(){const a="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";return Array.from({length:6},()=>a[Math.floor(Math.random()*a.length)]).join("");}
function settings(){return {...DEFAULT_SETTINGS,...(shared.settings||{})};}
function activeRooms(){const s=settings();return ["lobby","office","evidence","loading",...(s.rooms>=5?["archive"]:[]),...(s.rooms>=6?["security"]:[])];}
function requiredEvidence(){return Object.keys(EVIDENCE).slice(0,Math.max(2,Math.min(4,settings().evidence)));}
function evidenceCount(){return requiredEvidence().filter(k=>shared[`evidence:${k}`]).length;}
function isHost(){return session?.host_id===window.currentProfile?.id;}
function lobbyView(){["authView","gameView","teamLobbyView"].forEach(id=>$("#"+id)?.classList.add("hidden"));$("#lobbyView")?.classList.remove("hidden");}
function teamLobbyView(){["authView","lobbyView","gameView"].forEach(id=>$("#"+id)?.classList.add("hidden"));$("#teamLobbyView")?.classList.remove("hidden");}
function gameView(){["authView","lobbyView","teamLobbyView"].forEach(id=>$("#"+id)?.classList.add("hidden"));$("#gameView")?.classList.remove("hidden");}
function getPrefs(){try{return {...DEFAULT_SETTINGS,...JSON.parse(localStorage.getItem(LOCAL_SETTINGS_KEY)||"{}")} }catch{return {...DEFAULT_SETTINGS};}}
function savePrefs(p){localStorage.setItem(LOCAL_SETTINGS_KEY,JSON.stringify(p));applyPrefs(p);}
function applyPrefs(p=getPrefs()){document.documentElement.dataset.graphics=p.graphics||"high";}
function beep(freq=440,duration=.09,type="sine",volume=.04){const p=getPrefs();if(!p.sounds)return;if(!audioContext)audioContext=new(window.AudioContext||window.webkitAudioContext)();const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.0001,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(Math.max(.0001,volume*p.masterVolume),audioContext.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,audioContext.currentTime+duration);o.connect(g).connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+duration+.02);}
function startMusic(){const p=getPrefs();if(!p.music||ambientTimer)return;if(!audioContext)audioContext=new(window.AudioContext||window.webkitAudioContext)();const notes=[110,130.81,146.83,98];let i=0;ambientTimer=setInterval(()=>beep(notes[i++%notes.length],.28,"sine",.012),1800);}
function stopMusic(){clearInterval(ambientTimer);ambientTimer=null;}

async function createGame(){if(!window.currentProfile)return;for(let i=0;i<5;i++){const code=randomCode();const{data,error}=await supabase.from("game_sessions").insert({code,host_id:window.currentProfile.id}).select().single();if(!error)return joinSessionRecord(data);if(error.code!=="23505")return toast(error.message);}toast("Could not generate a unique game code.");}
async function joinByCode(code){const cleaned=code.trim().toUpperCase();const{data,error}=await supabase.from("game_sessions").select("*").eq("code",cleaned).eq("status","active").single();if(error||!data)return toast("Game not found or already finished.");const{count}=await supabase.from("session_players").select("*",{count:"exact",head:true}).eq("session_id",data.id);if(count>=CONFIG.MAX_PLAYERS)return toast("That game is full.");return joinSessionRecord(data);}
async function joinSessionRecord(record){session=record;const{data,error}=await supabase.from("session_players").upsert({session_id:session.id,user_id:window.currentProfile.id,room:"lobby",is_hidden:false},{onConflict:"session_id,user_id"}).select().single();if(error)return toast(error.message);sessionPlayer=data;currentRoom=data.room||"lobby";const{data:states}=await supabase.from("game_state").select("state_key,state_value").eq("session_id",session.id);shared=Object.fromEntries((states||[]).map(x=>[x.state_key,x.state_value]));if(isHost()&&!shared.settings)await setState("settings",DEFAULT_SETTINGS);if(!shared["visited:lobby"])await setState("visited:lobby",{visited:true});$("#gameCodeLabel").textContent=`Team code ${session.code}`;$("#teamCodeLarge").textContent=session.code;$("#teamLobbyProfile").textContent=`${window.currentProfile.nickname} · @${window.currentProfile.username}`;if(shared["game:started"])gameView();else teamLobbyView();await loadEverything();subscribe();startMusic();}
async function loadEverything(){if(!session)return;const[p,s,m]=await Promise.all([supabase.from("session_players").select("user_id,room,is_hidden,profiles(username,nickname)").eq("session_id",session.id),supabase.from("game_state").select("state_key,state_value").eq("session_id",session.id),supabase.from("messages").select("id,user_id,body,created_at,profiles(username,nickname)").eq("session_id",session.id).order("created_at").limit(80)]);players=p.data||[];shared=Object.fromEntries((s.data||[]).map(x=>[x.state_key,x.state_value]));renderLobby();renderMessages(m.data||[]);if(shared["game:started"])renderAll();}
function subscribe(){if(channel)supabase.removeChannel(channel);channel=supabase.channel(`game:${session.id}`).on("postgres_changes",{event:"*",schema:"public",table:"session_players",filter:`session_id=eq.${session.id}`},loadEverything).on("postgres_changes",{event:"*",schema:"public",table:"game_state",filter:`session_id=eq.${session.id}`},payload=>{if(payload.new?.state_key)shared[payload.new.state_key]=payload.new.state_value;renderLobby();if(shared["game:started"])renderAll();}).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`session_id=eq.${session.id}`},async()=>{const{data}=await supabase.from("messages").select("id,user_id,body,created_at,profiles(username,nickname)").eq("session_id",session.id).order("created_at").limit(80);renderMessages(data||[]);}).subscribe();}
async function setState(key,value){if(!session)return;shared[key]=value;renderLobby();if(shared["game:started"])renderAll();const{error}=await supabase.from("game_state").upsert({session_id:session.id,state_key:key,state_value:value,updated_by:window.currentProfile.id},{onConflict:"session_id,state_key"});if(error)toast(error.message);}
function renderLobby(){if(!session)return;$("#teamCodeLarge").textContent=session.code;$("#hostBadge").textContent=isHost()?"HOST":"PLAYER";$("#startGameBtn").disabled=!isHost();$("#startHint").textContent=isHost()?"Configure the operation, then start when everyone is ready.":"Waiting for the host to start the operation.";$("#lobbyPlayerList").innerHTML=players.map(p=>`<div class="lobby-player"><span class="player-avatar">${esc((p.profiles?.nickname||"D").slice(0,1).toUpperCase())}</span><div><strong>${esc(p.profiles?.nickname||"Detective")}</strong><small>@${esc(p.profiles?.username||"detective")}</small></div>${p.user_id===session.host_id?'<b class="host-label">HOST</b>':''}</div>`).join("");renderHostSettings();}
function renderHostSettings(){const root=$("#hostSettingsForm");if(!root)return;const s=settings();root.innerHTML=`<label>Difficulty<select data-setting="difficulty"><option value="easy">Easy</option><option value="normal">Normal</option><option value="hard">Hard</option></select></label><label>Evidence required <output>${s.evidence}</output><input data-setting="evidence" type="range" min="2" max="4" value="${s.evidence}"></label><label>Rooms <output>${s.rooms}</output><input data-setting="rooms" type="range" min="4" max="6" value="${s.rooms}"></label><label>Guards <output>${s.guards}</output><input data-setting="guards" type="range" min="0" max="3" value="${s.guards}"></label><label>Warning before arrival <output>${s.guardWarning}s</output><input data-setting="guardWarning" type="range" min="3" max="10" value="${s.guardWarning}"></label><label>Capture time after arrival <output>${s.guardCapture}s</output><input data-setting="guardCapture" type="range" min="2" max="8" value="${s.guardCapture}"></label>`;root.querySelector('[data-setting="difficulty"]').value=s.difficulty;root.querySelectorAll("input").forEach(input=>input.addEventListener("input",e=>{const out=e.target.parentElement.querySelector("output");if(out)out.textContent=e.target.value+(e.target.dataset.setting.includes("guard")?"s":"");}));root.querySelectorAll("select,input").forEach(el=>el.disabled=!isHost());root.onchange=async e=>{if(!isHost())return;const el=e.target;if(!el.dataset.setting)return;const next={...s,[el.dataset.setting]:el.type==="range"?Number(el.value):el.value};await setState("settings",next);beep(520,.06);};}
async function startGame(){if(!isHost())return;await setState("game:started",{started:true,by:window.currentProfile.id,at:Date.now()});gameView();beep(660,.14,"triangle",.06);renderAll();}

function renderAll(){if(!session)return;renderScene();renderMap();renderPlayers();renderEvidenceCount();}
function renderScene(){const room=ROOMS[currentRoom];if(!room)return;const scene=$("#scene");scene.className=`scene ${room.cls}`;$("#roomTitle").textContent=room.name;$("#sceneLabel").textContent=room.name.toUpperCase();const hotspots=[];const exits={...room.exits};if(currentRoom==="office"&&!activeRooms().includes("archive")){delete exits.archive;exits.evidence="Evidence Room";}if(currentRoom==="evidence"){delete exits.archive;delete exits.security;if(activeRooms().includes("archive"))exits.archive="Archive";if(activeRooms().includes("security"))exits.security="Security";}const exitPositions=[[3,42,18,35],[79,38,17,38],[39,3,22,18],[35,75,28,18]];let i=0;for(const[dest,label]of Object.entries(exits)){if(!activeRooms().includes(dest))continue;hotspots.push(hotspot(`Go: ${label}`,exitPositions[i++%exitPositions.length],()=>moveTo(dest),"exit"));}if(currentRoom==="office"&&!shared["evidence:keycard"])hotspots.push(hotspot("Desk drawer",HOTSPOTS.office.drawer,collectKeycard,"sprite-hotspot"));if(currentRoom==="office"&&!shared["puzzle:morse"])hotspots.push(hotspot("Radio receiver",HOTSPOTS.office.radio,openMorse,"sprite-hotspot"));if(currentRoom==="archive"&&!shared["evidence:photo"])hotspots.push(hotspot("File box A-17",HOTSPOTS.archive.file,collectPhoto,"sprite-hotspot"));if(["office","archive","security","evidence"].includes(currentRoom))hotspots.push(hotspot(hidden?"Leave hiding place":"Hide",[7,64,18,24],toggleHide,"hide-hotspot"));if(currentRoom==="security")hotspots.push(hotspot("Guard monitor",HOTSPOTS.security.monitor,()=>toast("The patrol route is visible. Wait for a clear window."),"sprite-hotspot"));if(currentRoom==="evidence"&&!shared["evidence:ledger"])hotspots.push(hotspot("Evidence locker 314",HOTSPOTS.evidence.locker,collectLedger,"sprite-hotspot"));if(currentRoom==="loading")hotspots.push(hotspot("Leave building",HOTSPOTS.loading.exit,attemptExtraction,"sprite-hotspot"));const root=$("#hotspots");root.innerHTML="";hotspots.forEach(x=>root.appendChild(x));$("#playerChips").innerHTML=players.filter(p=>p.room===currentRoom).map(p=>`<span class="player-chip">${p.is_hidden?"▣ ":"● "}${esc(p.profiles?.nickname||"Detective")}</span>`).join("");}
function hotspot(label,[x,y,w,h],fn,cls=""){const b=document.createElement("button");b.className=`hotspot ${cls}`;b.style.cssText=`left:${x}%;top:${y}%;width:${w}%;height:${h}%`;b.innerHTML=`<span>${esc(label)}</span>`;b.addEventListener("click",fn);return b;}
function renderMap(){const map=$("#minimap");map.innerHTML="";Object.entries(ROOMS).filter(([k])=>activeRooms().includes(k)).forEach(([key,r])=>{const el=document.createElement("div");el.className=`map-room ${shared[`visited:${key}`]?"visited":""} ${key===currentRoom?"current":""}`;el.style.gridColumn=r.map[0]+1;el.style.gridRow=3-r.map[1];const here=players.filter(p=>p.room===key);el.innerHTML=`${shared[`visited:${key}`]||key===currentRoom?esc(r.name):"Unknown"}<div class="dots">${here.map(()=>'<i class="dot"></i>').join("")}</div>`;map.appendChild(el);});}
function renderPlayers(){$("#onlineCount").textContent=`${players.length} online`;$("#playerList").innerHTML=players.map(p=>`<div class="player-row"><span>${esc(p.profiles?.nickname||"Detective")}</span><small>${esc(ROOMS[p.room]?.name||p.room)}${p.is_hidden?" · hidden":""}</small></div>`).join("");}
function renderEvidenceCount(){$("#evidenceCounter").textContent=`Evidence ${evidenceCount()}/${requiredEvidence().length}`;}
async function moveTo(room){if(!activeRooms().includes(room))return toast("That room is closed for this operation.");if(room==="archive"&&!shared["evidence:keycard"])return toast("The archive reader needs a keycard.");if(room==="evidence"&&!shared["puzzle:lockpick"])return openLockpick();currentRoom=room;hidden=false;await Promise.all([supabase.from("session_players").update({room,is_hidden:false,last_seen:new Date().toISOString()}).eq("session_id",session.id).eq("user_id",window.currentProfile.id),setState(`visited:${room}`,{visited:true})]);renderAll();beep(240,.08,"triangle");maybeTriggerGuard();}
async function collectKeycard(){await setState("evidence:keycard",{foundBy:window.currentProfile.id,at:Date.now()});await awardClue();toast("Archive keycard added to the shared evidence bag.");beep(700,.1);}
async function collectPhoto(){await setState("evidence:photo",{foundBy:window.currentProfile.id,at:Date.now()});await awardClue();toast("Security photograph recovered.");beep(760,.1);}
async function collectLedger(){if(!shared["puzzle:morse"])return toast("You do not know which locker contains the ledger yet.");await setState("evidence:ledger",{foundBy:window.currentProfile.id,at:Date.now()});await awardClue();toast("Black ledger recovered. Get it to the exit.");beep(820,.12,"triangle");}
async function awardClue(){await supabase.rpc("increment_stat",{target_user:window.currentProfile.id,stat_name:"clues_found",amount:1});}
function openMorse(){const d=$("#puzzleDialog");$("#puzzleContent").innerHTML=`<div class="puzzle-grid"><div class="eyebrow">RADIO INTERCEPT</div><h2>Decode the Morse message</h2><p>Translate the transmission. Spaces separate letters and a slash separates words.</p><div class="morse-box">.-.. . -.. --. . .-. / ...-- .---- ....-</div><div class="code-input"><input id="morseAnswer" placeholder="decoded message"><button id="morseSubmit" class="primary">Decode</button></div><p class="fineprint">Reference: .- A · -... B · -.-. C · -.. D · . E · --. G · .... H · .-.. L · -- M · .-. R · ... S · - T · ...-- 3 · .---- 1 · ....- 4</p></div>`;d.showModal();$("#morseSubmit").onclick=async()=>{const ans=$("#morseAnswer").value.trim().toUpperCase().replace(/\s+/g," ");if(ans!=="LEDGER 314")return toast("That translation is not correct.");await setState("puzzle:morse",{solvedBy:window.currentProfile.id});await setState("evidence:morse",{foundBy:window.currentProfile.id,at:Date.now()});await awardClue();d.close();toast("Transmission decoded: LEDGER 314.");beep(880,.16,"triangle");};}
function openLockpick(){const d=$("#puzzleDialog");const ranges={easy:[75,105],normal:[82,98],hard:[87,93]},[lo,hi]=ranges[settings().difficulty]||ranges.normal;$("#puzzleContent").innerHTML=`<div class="puzzle-grid"><div class="eyebrow">MECHANICAL LOCK</div><h2>Pick the evidence-room lock</h2><p>Hold <b>A</b> or <b>D</b> to rotate the pick. Press <b>Space</b> inside the highlighted zone.</p><div class="lockpick"><div class="lock-core"><div class="lock-target"></div><div id="lockLine" class="lock-line"></div></div></div><small id="lockStatus">Alignment: 0° / target ${lo}–${hi}°</small></div>`;d.showModal();let angle=0;const keys=new Set();const update=()=>{angle=Math.max(-90,Math.min(180,angle+(keys.has("d")?2.3:0)-(keys.has("a")?2.3:0)));const line=$("#lockLine");if(line)line.style.transform=`rotate(${angle}deg)`;const s=$("#lockStatus");if(s)s.textContent=`Alignment: ${Math.round(angle)}° / target ${lo}–${hi}°`;};const interval=setInterval(update,16);const kd=async e=>{const k=e.key.toLowerCase();if(["a","d"].includes(k))keys.add(k);if(e.code==="Space"){e.preventDefault();if(angle>=lo&&angle<=hi){cleanup();await setState("puzzle:lockpick",{solvedBy:window.currentProfile.id});await supabase.rpc("increment_stat",{target_user:window.currentProfile.id,stat_name:"puzzles_solved",amount:1});d.close();toast("Lock opened.");beep(920,.16,"triangle");}else beep(130,.08,"sawtooth");}};const ku=e=>keys.delete(e.key.toLowerCase());const cleanup=()=>{clearInterval(interval);window.removeEventListener("keydown",kd);window.removeEventListener("keyup",ku)};window.addEventListener("keydown",kd);window.addEventListener("keyup",ku);d.addEventListener("close",cleanup,{once:true});}
async function toggleHide(){hidden=!hidden;await supabase.from("session_players").update({is_hidden:hidden,last_seen:new Date().toISOString()}).eq("session_id",session.id).eq("user_id",window.currentProfile.id);renderAll();beep(hidden?180:360,.12);}
function maybeTriggerGuard(){const s=settings();if(s.guards<=0||!currentRoom||currentRoom==="lobby")return;const chance={easy:.12,normal:.2,hard:.32}[s.difficulty]||.2;if(Math.random()>chance)return;clearTimeout(guardTimer);guardTimer=setTimeout(()=>guardApproach(s),800+Math.random()*1800);}
function guardApproach(s){let seconds=s.guardWarning;$("#guardCountdown").textContent=seconds;$("#guardBanner").classList.remove("hidden");beep(90,.15,"square",.08);clearInterval(guardCountdownTimer);guardCountdownTimer=setInterval(()=>{seconds--;$("#guardCountdown").textContent=Math.max(0,seconds);beep(110,.07,"square",.04);if(seconds<=0){clearInterval(guardCountdownTimer);guardArrived(s)}},1000);}
function guardArrived(s){$("#guardBanner").classList.add("hidden");if(hidden){toast("The guard passed without finding you.");beep(300,.1);return;}let seconds=s.guardCapture;toast(`Guard spotted you. You have ${seconds}s to hide.`);let remaining=seconds;$("#guardCountdown").textContent=remaining;$("#guardBanner").classList.remove("hidden");guardCountdownTimer=setInterval(()=>{remaining--;$("#guardCountdown").textContent=Math.max(0,remaining);if(remaining<=0){clearInterval(guardCountdownTimer);$("#guardBanner").classList.add("hidden");capturePlayer();}},1000);}
async function capturePlayer(){await supabase.rpc("increment_stat",{target_user:window.currentProfile.id,stat_name:"times_caught",amount:1});hidden=false;currentRoom="lobby";await supabase.from("session_players").update({room:"lobby",is_hidden:false,last_seen:new Date().toISOString()}).eq("session_id",session.id).eq("user_id",window.currentProfile.id);renderAll();toast("Security caught you. You were returned to the main lobby.");beep(70,.25,"sawtooth",.08);}
async function attemptExtraction(){const req=requiredEvidence();if(evidenceCount()<req.length)return toast(`You need all ${req.length} required evidence items.`);await setState(`extracted:${window.currentProfile.id}`,{at:Date.now()});toast("You made it outside. Wait for the rest of the team.");beep(600,.18,"triangle");const fresh=await supabase.from("session_players").select("user_id").eq("session_id",session.id);const all=(fresh.data||[]).every(p=>shared[`extracted:${p.user_id}`]);if(all&&fresh.data?.length){await supabase.rpc("complete_game",{session_id:session.id});await supabase.rpc("increment_stat",{target_user:window.currentProfile.id,stat_name:"games_won",amount:1});toast("Case closed. The whole team extracted.");}}
function renderMessages(messages){const root=$("#chatMessages");if(!root)return;root.innerHTML=messages.map(m=>`<div class="message"><b>${esc(m.profiles?.nickname||"Detective")}</b>${esc(m.body)}</div>`).join("");root.scrollTop=root.scrollHeight;}
async function sendMessage(){const input=$("#chatInput"),body=input.value.trim();if(!body||!session)return;input.value="";const{error}=await supabase.from("messages").insert({session_id:session.id,user_id:window.currentProfile.id,body});if(error)toast(error.message);else beep(520,.05);}
function openNotes(){$("#notesText").value=localStorage.getItem(NOTES_KEY())||"";$("#notesDialog").showModal();$("#notesText").focus();}
function saveNotes(){localStorage.setItem(NOTES_KEY(),$("#notesText").value);$("#notesDialog").close();toast("Notes saved locally.");beep(520,.06);}
function openSettings(){const d=$("#settingsDialog"),p=getPrefs();$("#settingsForm").innerHTML=`<label>Sound effects<select data-pref="sounds"><option value="true">On</option><option value="false">Off</option></select></label><label>Music<select data-pref="music"><option value="true">On</option><option value="false">Off</option></select></label><label>Graphics<select data-pref="graphics"><option value="high">High</option><option value="low">Low</option></select></label><label>Master volume <output>${Math.round(p.masterVolume*100)}%</output><input data-pref="masterVolume" type="range" min="0" max="1" step=".05" value="${p.masterVolume}"></label>`;$("#settingsForm").querySelectorAll("select").forEach(x=>x.value=String(p[x.dataset.pref]));$("#settingsForm").querySelector('[data-pref="masterVolume"]').addEventListener("input",e=>e.target.parentElement.querySelector("output").textContent=`${Math.round(e.target.value*100)}%`);d.showModal();}
function applySettingsDialog(){const p=getPrefs();$("#settingsForm").querySelectorAll("select,input").forEach(el=>{p[el.dataset.pref]=el.type==="range"?Number(el.value):el.value==="true"?true:el.value==="false"?false:el.value;});savePrefs(p);if(p.music)startMusic();else stopMusic();$("#settingsDialog").close();toast("Settings applied.");beep(520,.06);}
function resetSettings(){savePrefs({...DEFAULT_SETTINGS});openSettings();}
function currentObjective(){if(!shared["evidence:keycard"])return"Objective: Search the Records Office and recover the archive keycard.";if(!shared["puzzle:morse"])return"Objective: Decode the radio transmission.";if(!shared["puzzle:lockpick"])return"Objective: Pick the Evidence Room lock.";if(requiredEvidence().some(k=>!shared[`evidence:${k}`]))return"Objective: Recover the remaining required evidence.";return"Objective: Take all required evidence to the Loading Bay and have every detective extract.";}
function openInventory(){const root=$("#inventoryList");root.innerHTML=Object.entries(EVIDENCE).filter(([k])=>shared[`evidence:${k}`]).map(([k,v])=>`<div class="evidence-item"><strong>${esc(v[0])}</strong><small>${esc(v[1])}</small></div>`).join("")||'<div class="empty-state">No evidence recovered yet.</div>';$("#inventoryDialog").showModal();}
async function leaveSession(){clearTimeout(guardTimer);clearInterval(guardCountdownTimer);stopMusic();if(channel)supabase.removeChannel(channel);channel=null;if(session&&window.currentProfile)await supabase.from("session_players").delete().eq("session_id",session.id).eq("user_id",window.currentProfile.id);session=null;sessionPlayer=null;players=[];shared={};currentRoom="lobby";hidden=false;lobbyView();}

$("#createGameBtn")?.addEventListener("click",createGame);$("#joinForm")?.addEventListener("submit",e=>{e.preventDefault();joinByCode($("#joinCode").value)});$("#startGameBtn")?.addEventListener("click",startGame);$("#copyCodeBtn")?.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(session.code)}catch{}toast("Team code copied.");});$("#leaveLobbyBtn")?.addEventListener("click",leaveSession);$("#leaveGameBtn")?.addEventListener("click",leaveSession);$("#chatForm")?.addEventListener("submit",e=>{e.preventDefault();sendMessage();});$("#inventoryBtn")?.addEventListener("click",openInventory);$("#hintBtn")?.addEventListener("click",()=>toast(currentObjective()));$("#notesBtn")?.addEventListener("click",openNotes);$("#saveNotesBtn")?.addEventListener("click",saveNotes);$("#clearNotesBtn")?.addEventListener("click",()=>{$("#notesText").value="";});$("#closeNotesBtn")?.addEventListener("click",()=>$("#notesDialog").close());$("#settingsBtn")?.addEventListener("click",openSettings);$("#teamLobbySettingsBtn")?.addEventListener("click",openSettings);$("#saveSettingsBtn")?.addEventListener("click",applySettingsDialog);$("#resetSettingsBtn")?.addEventListener("click",resetSettings);$("#closeSettingsBtn")?.addEventListener("click",()=>$("#settingsDialog").close());$("#closePuzzleBtn")?.addEventListener("click",()=>$("#puzzleDialog").close());$("#closeInventoryBtn")?.addEventListener("click",()=>$("#inventoryDialog").close());
