// Version 3.0.0
// Supabase Realtime dependency is loaded by js/supabase.js.
import { supabase } from "./supabase.js";
import { CONFIG } from "./config.js";
import { toast } from "./auth.js";

const $ = (s) => document.querySelector(s);
const esc = (value = "") => { const d = document.createElement("div"); d.textContent = value; return d.innerHTML; };
const uid = () => window.currentProfile?.id || "guest";
const LOCAL_SETTINGS_KEY = "nsd-settings-v3";
const RUN_LOG_KEY = () => `nsd-runs-${uid()}`;
const NOTES_KEY = () => `nsd-notes-${uid()}`;
const DEFAULT_SETTINGS = {
  difficulty: "normal", evidence: 4, rooms: 8, guards: 1, guardWarning: 5, guardCapture: 45,
  lives: 3, timeLimit: 240, music: true, sounds: true, masterVolume: .65,
  graphics: "high", speedRun: false, visibleTimer: true, runDestination: "finish"
};
const SHOP_ITEMS = [
  { id: "clue_bonus", name: "Evidence Finder", price: 120, desc: "+10% coins from evidence." },
  { id: "explorer", name: "Explorer", price: 220, desc: "+20% coins for discovering every room." },
  { id: "survivor", name: "Survivor", price: 300, desc: "+15% completion coins." },
  { id: "time_boost", name: "Extra Minute", price: 450, desc: "+60 seconds to your own runs." }
];
const MODIFIERS = [
  { id: "bright", name: "Bright Evidence", score: -10, desc: "Evidence hotspots are more visible." },
  { id: "slow_guards", name: "Slow Patrols", score: -15, desc: "Guards take longer to arrive." },
  { id: "fragile", name: "Fragile", score: 20, desc: "Lose an extra half-life when captured." },
  { id: "dark", name: "Blackout", score: 25, desc: "Room names stay hidden until discovered." },
  { id: "rush", name: "Hard Rush", score: 35, desc: "The time limit is reduced by 20%." }
];
const ROOM_TYPES = [
  ["office","Records Office"],["archive","Archive Stacks"],["security","Security Control"],["evidence","Evidence Room"],
  ["loading","Loading Bay"],["lab","Forensics Lab"],["server","Server Room"],["basement","Basement Storage"],["library","Case Library"],
  ["workshop","Maintenance Workshop"],["hall","North Hall"],["vault","Evidence Vault"],["break","Break Room"],["roof","Roof Access"],
  ["garage","Service Garage"],["reception","Reception"],["interview","Interview Room"],["records","Old Records"],["generator","Generator Room"],["control","Operations Control"]
];
const PUZZLES = [
  { id:"morse", name:"Morse Decoder", type:"morse", prompt:"Decode the transmission: .-.. . -.. --. . .-. / ...-- .---- ....-", answer:"LEDGER 314" },
  { id:"lockpick", name:"Mechanical Lock", type:"lock", prompt:"Align the pick inside the target zone." },
  { id:"keypad", name:"Keypad", type:"keypad", prompt:"Enter the four-digit access code shown by the clue.", answer:"3141" },
  { id:"sequence", name:"Sequence", type:"sequence", prompt:"What number comes next? 2, 4, 8, 16, ?", answer:"32" },
  { id:"anagram", name:"Anagram", type:"anagram", prompt:"Rearrange: R A C H I V E", answer:"ARCHIVE" },
  { id:"symbols", name:"Symbol Match", type:"symbols", prompt:"Select the symbol that matches the target: ▲ ● ■", answer:"■" },
  { id:"switch", name:"Switchboard", type:"switch", prompt:"Turn switches on until the indicator reaches 3/3." },
  { id:"frequency", name:"Radio Frequency", type:"frequency", prompt:"Tune the dial to 73.", answer:"73" },
  { id:"memory", name:"Memory Grid", type:"memory", prompt:"Repeat the highlighted sequence." },
  { id:"directions", name:"Directional Lock", type:"directions", prompt:"Enter the route: N E E S W", answer:"NEESW" },
  { id:"colors", name:"Color Cipher", type:"colors", prompt:"Red=1, Blue=2, Green=3. Decode Blue-Green-Red.", answer:"231" },
  { id:"math", name:"Evidence Arithmetic", type:"math", prompt:"17 + 8 × 2 = ?", answer:"33" },
  { id:"pattern", name:"Pattern Grid", type:"pattern", prompt:"Complete the pattern: 1, 1, 2, 3, 5, ?", answer:"8" },
  { id:"terminal", name:"Terminal Command", type:"terminal", prompt:"Type the command: OPEN VAULT", answer:"OPEN VAULT" },
  { id:"rescue", name:"Rescue Lock", type:"rescue", prompt:"Solve the rescue lock to free your teammate." }
];
let session = null, sessionPlayer = null, players = [], shared = {}, channel = null;
let rooms = [], currentRoom = null, hidden = false;
let guardTimer = null, guardCountdownTimer = null, gameTimer = null, gameStartedAt = 0;
let audioContext = null, ambientTimer = null, activePuzzle = null;

function getPrefs(){ try { return {...DEFAULT_SETTINGS, ...JSON.parse(localStorage.getItem(LOCAL_SETTINGS_KEY) || "{}")} } catch { return {...DEFAULT_SETTINGS}; } }
function savePrefs(p){ localStorage.setItem(LOCAL_SETTINGS_KEY, JSON.stringify(p)); applyPrefs(p); }
function applyPrefs(p=getPrefs()){ document.documentElement.dataset.graphics = p.graphics || "high"; }
function settings(){ return {...DEFAULT_SETTINGS, ...(shared.settings || {})}; }
function activeModifiers(){ return settings().modifiers || []; }
function modifierScore(){ return activeModifiers().reduce((n,id)=>n+(MODIFIERS.find(x=>x.id===id)?.score||0),0); }
function isHost(){ return session?.host_id === uid(); }
function isCapturedSelf(){ return Boolean(shared[`captured:${uid()}`]); }
function requiredEvidence(){ const count = Math.max(2, Math.min(15, Number(settings().evidence)||4)); return (shared.evidencePool || []).slice(0, count); }
function evidenceCount(){ return requiredEvidence().filter(k=>shared[`evidence:${k}`]).length; }
function roomById(id){ return rooms.find(r=>r.id===id); }
function roomByIdFrom(list,id){ return list.find(r=>r.id===id); }
function randomCode(){ const a="ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; return Array.from({length:6},()=>a[Math.floor(Math.random()*a.length)]).join(""); }
function clamp(n,a,b){ return Math.max(a,Math.min(b,n)); }
function shuffle(a){ return [...a].sort(()=>Math.random()-.5); }
function lobbyView(){ ["authView","gameView","teamLobbyView"].forEach(id=>$("#"+id)?.classList.add("hidden")); $("#lobbyView")?.classList.remove("hidden"); renderMainMenu(); }
function teamLobbyView(){ ["authView","lobbyView","gameView"].forEach(id=>$("#"+id)?.classList.add("hidden")); $("#teamLobbyView")?.classList.remove("hidden"); }
function gameView(){ ["authView","lobbyView","teamLobbyView"].forEach(id=>$("#"+id)?.classList.add("hidden")); $("#gameView")?.classList.remove("hidden"); }

function beep(freq=440,duration=.09,type="sine",volume=.04){ const p=getPrefs(); if(!p.sounds)return; if(!audioContext)audioContext=new(window.AudioContext||window.webkitAudioContext)(); const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.0001,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(Math.max(.0001,volume*p.masterVolume),audioContext.currentTime+.01);g.gain.exponentialRampToValueAtTime(.0001,audioContext.currentTime+duration);o.connect(g).connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+duration+.02); }
function startMusic(){ const p=getPrefs();if(!p.music||ambientTimer)return;if(!audioContext)audioContext=new(window.AudioContext||window.webkitAudioContext)();const notes=[110,130.81,146.83,98];let i=0;ambientTimer=setInterval(()=>{if(p.music)musicTone(notes[i++%notes.length]);},1800); }
function musicTone(freq){if(!audioContext)return;const o=audioContext.createOscillator(),g=audioContext.createGain();o.frequency.value=freq;o.type="sine";g.gain.value=.006*getPrefs().masterVolume;o.connect(g).connect(audioContext.destination);o.start();o.stop(audioContext.currentTime+.22);}
function stopMusic(){clearInterval(ambientTimer);ambientTimer=null;}

function generateRooms(count){
  const cells=Array.from({length:20},(_,i)=>i),selected=shuffle(cells).slice(0,clamp(count,4,20)).sort((a,b)=>a-b),set=new Set(selected),out=[];
  for(const cell of selected){const type=ROOM_TYPES[out.length%ROOM_TYPES.length];out.push({id:`r${cell}`,type:type[0],name:type[1],cell,x:cell%5,y:Math.floor(cell/5),neighbors:[],tags:[]});}
  const byCell=new Map(out.map(r=>[r.cell,r]));
  for(const r of out){for(const n of [r.cell-5,r.cell+5,r.cell-1,r.cell+1]){if(byCell.has(n)&&((n%5)===(r.cell%5)||Math.floor(n/5)===Math.floor(r.cell/5)))r.neighbors.push(byCell.get(n).id);}}
  const link=(a,b)=>{if(!a.neighbors.includes(b.id))a.neighbors.push(b.id);if(!b.neighbors.includes(a.id))b.neighbors.push(a.id);};
  const component=(start)=>{const seen=new Set([start.id]),q=[start];while(q.length){const x=q.shift();for(const id of x.neighbors){const n=roomByIdFrom(out,id);if(n&&!seen.has(n.id)){seen.add(n.id);q.push(n);}}}return seen;};
  for(const r of out){if(!r.neighbors.length){const target=out.filter(x=>x!==r).sort((a,b)=>Math.abs(a.x-r.x)+Math.abs(a.y-r.y)-(Math.abs(b.x-r.x)+Math.abs(b.y-r.y)))[0];if(target)link(r,target);}}
  while(component(out[0]).size<out.length){const main=component(out[0]),ar=out.find(r=>r.id===main.values().next().value),outside=out.filter(r=>!main.has(r.id));const br=outside.sort((x,y)=>Math.abs(x.x-ar.x)+Math.abs(x.y-ar.y)-(Math.abs(y.x-ar.x)+Math.abs(y.y-ar.y)))[0];link(ar,br);}
  for(const r of out){const candidates=out.filter(x=>x!==r&&!r.neighbors.includes(x.id)&&Math.abs(x.x-r.x)+Math.abs(x.y-r.y)<=3);if(candidates.length&&Math.random()<.28)link(r,candidates[Math.floor(Math.random()*candidates.length)]);}
  out[0].type="reception";out[0].name="Reception";out[out.length-1].type="loading";out[out.length-1].name="Loading Bay";return out;
}
function buildEvidencePool(){return shuffle(Array.from({length:20},(_,i)=>`e${i+1}`));}
function buildPuzzleAssignments(){return shuffle(PUZZLES.filter(p=>p.type!=="rescue").map(p=>p.id));}

async function createGame(){if(!window.currentProfile)return;for(let i=0;i<5;i++){const code=randomCode();const{data,error}=await supabase.from("game_sessions").insert({code,host_id:uid()}).select().single();if(!error)return joinSessionRecord(data);if(error.code!=="23505")return toast(error.message);}toast("Could not generate a unique game code.");}
async function joinByCode(code){const cleaned=code.trim().toUpperCase();const{data,error}=await supabase.from("game_sessions").select("*").eq("code",cleaned).eq("status","active").single();if(error||!data)return toast("Game not found or already finished.");const{count}=await supabase.from("session_players").select("*",{count:"exact",head:true}).eq("session_id",data.id);if(count>=CONFIG.MAX_PLAYERS)return toast("That game is full.");return joinSessionRecord(data);}
async function joinSessionRecord(record){session=record;const{data,error}=await supabase.from("session_players").upsert({session_id:session.id,user_id:uid(),room:"lobby",is_hidden:false},{onConflict:"session_id,user_id"}).select().single();if(error)return toast(error.message);sessionPlayer=data;currentRoom=data.room&&data.room!=="lobby"?data.room:"r0";const{data:states}=await supabase.from("game_state").select("state_key,state_value").eq("session_id",session.id);shared=Object.fromEntries((states||[]).map(x=>[x.state_key,x.state_value]));if(isHost()&&!shared.settings)await setState("settings",DEFAULT_SETTINGS);if(isHost()&&!shared.rooms)await initializeOperation();if(!shared["visited:r0"])await setState("visited:r0",{visited:true});$("#gameCodeLabel").textContent=`Team code ${session.code}`;$("#teamCodeLarge").textContent=session.code;$("#teamLobbyProfile").textContent=`${window.currentProfile.nickname} · @${window.currentProfile.username}`;if(shared["game:started"])gameView();else teamLobbyView();await loadEverything();subscribe();startMusic();}
async function initializeOperation(){rooms=generateRooms(settings().rooms);const pool=buildEvidencePool(),puzzles=buildPuzzleAssignments(),assigned={};rooms.forEach((r,i)=>assigned[r.id]=puzzles[i%puzzles.length]);await setState("rooms",rooms);await setState("evidencePool",pool);await setState("puzzles",puzzles);for(const r of rooms)await setState(`puzzle:${r.id}`,assigned[r.id]);await setState("game:lives",{});await setState("game:started",null);}
async function loadEverything(){if(!session)return;const[p,s,m]=await Promise.all([supabase.from("session_players").select("user_id,room,is_hidden,profiles(username,nickname)").eq("session_id",session.id),supabase.from("game_state").select("state_key,state_value").eq("session_id",session.id),supabase.from("messages").select("id,user_id,body,created_at,profiles(username,nickname)").eq("session_id",session.id).order("created_at").limit(100)]);players=p.data||[];shared=Object.fromEntries((s.data||[]).map(x=>[x.state_key,x.state_value]));rooms=shared.rooms||rooms;if(!rooms.length)rooms=generateRooms(settings().rooms);renderLobby();renderMessages(m.data||[]);if(shared["game:started"])renderAll();}
function subscribe(){if(channel)supabase.removeChannel(channel);channel=supabase.channel(`game:${session.id}`).on("postgres_changes",{event:"*",schema:"public",table:"session_players",filter:`session_id=eq.${session.id}`},loadEverything).on("postgres_changes",{event:"*",schema:"public",table:"game_state",filter:`session_id=eq.${session.id}`},payload=>{if(payload.new?.state_key)shared[payload.new.state_key]=payload.new.state_value;rooms=shared.rooms||rooms;renderLobby();if(shared["game:started"])renderAll();}).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`session_id=eq.${session.id}`},async()=>{const{data}=await supabase.from("messages").select("id,user_id,body,created_at,profiles(username,nickname)").eq("session_id",session.id).order("created_at").limit(100);renderMessages(data||[]);}).subscribe();}
async function setState(key,value){if(!session)return;shared[key]=value;if(key==="rooms")rooms=value;renderLobby();if(shared["game:started"])renderAll();const{error}=await supabase.from("game_state").upsert({session_id:session.id,state_key:key,state_value:value,updated_by:uid()},{onConflict:"session_id,state_key"});if(error)toast(error.message);}

function renderLobby(){if(!session)return;$("#teamCodeLarge").textContent=session.code;$("#hostBadge").textContent=isHost()?"HOST":"PLAYER";$("#startGameBtn").disabled=!isHost();$("#startHint").textContent=isHost()?"Configure the operation, then start when everyone is ready.":"Waiting for the host to start the operation.";$("#lobbyPlayerList").innerHTML=players.map(p=>`<div class="lobby-player"><span class="player-avatar">${esc((p.profiles?.nickname||"D").slice(0,1).toUpperCase())}</span><div><strong>${esc(p.profiles?.nickname||"Detective")}</strong><small>@${esc(p.profiles?.username||"detective")}</small></div>${p.user_id===session.host_id?'<b class="host-label">HOST</b>':''}</div>`).join("");renderHostSettings();}
function renderHostSettings(){const root=$("#hostSettingsForm");if(!root)return;const s=settings();root.innerHTML=`<label>Difficulty<select data-setting="difficulty"><option value="easy">Easy</option><option value="normal">Normal</option><option value="hard">Hard</option></select></label><label>Evidence required <output>${s.evidence}</output><input data-setting="evidence" type="range" min="2" max="15" value="${s.evidence}"></label><label>Rooms <output>${s.rooms}</output><input data-setting="rooms" type="range" min="4" max="20" value="${s.rooms}"></label><label>Guards <output>${s.guards}</output><input data-setting="guards" type="range" min="0" max="8" value="${s.guards}"></label><label>Warning before arrival <output>${s.guardWarning}s</output><input data-setting="guardWarning" type="range" min="2" max="10" value="${s.guardWarning}"></label><label>Capture time <output>${s.guardCapture}s</output><input data-setting="guardCapture" type="range" min="45" max="60" value="${s.guardCapture}"></label><label>Lives <output>${s.lives}</output><input data-setting="lives" type="range" min="3" max="5" value="${s.lives}"></label><label>Time limit <output>${s.timeLimit}s</output><input data-setting="timeLimit" type="range" min="200" max="300" value="${s.timeLimit}"></label><label>Modifiers <div class="modifier-grid">${MODIFIERS.map(m=>`<label><input type="checkbox" data-modifier="${m.id}" ${activeModifiers().includes(m.id)?"checked":""}> ${m.name}</label>`).join("")}</div></label>`;root.querySelector('[data-setting="difficulty"]').value=s.difficulty;root.querySelectorAll('input[type="range"]').forEach(input=>input.addEventListener("input",e=>{const out=e.target.parentElement.querySelector("output");if(out)out.textContent=e.target.value+(e.target.dataset.setting.toLowerCase().includes("warning")||e.target.dataset.setting.toLowerCase().includes("capture")||e.target.dataset.setting.toLowerCase().includes("timelimit")?"s":"");}));root.querySelectorAll("select,input").forEach(el=>el.disabled=!isHost());root.onchange=async e=>{if(!isHost())return;const el=e.target;if(el.dataset.modifier){const next={...s,modifiers:[...new Set((s.modifiers||[]).filter(x=>x!==el.dataset.modifier).concat(el.checked?[el.dataset.modifier]:[]))]};return setState("settings",next);}if(!el.dataset.setting)return;const next={...s,[el.dataset.setting]:el.type==="range"?Number(el.value):el.value};await setState("settings",next);beep(520,.06);};}
async function startGame(){if(!isHost())return;const s=settings();if(s.evidence>s.rooms)return toast("Evidence required cannot exceed the number of rooms. Increase rooms or reduce evidence.");await setState("game:started",{started:true,by:uid(),at:Date.now()});await setState("game:startedAt",Date.now());gameStartedAt=Date.now();rooms=shared.rooms||rooms;gameView();renderAll();startGameTimer();beep(660,.14,"triangle",.06);}

function renderAll(){if(!session)return;renderScene();renderMap();renderPlayers();renderEvidenceCount();renderGameHud();}
function renderScene(){const room=roomById(currentRoom)||rooms[0];if(!room)return;const scene=$("#scene");scene.className=`scene room-${room.type}`;$("#roomTitle").textContent=room.name;$("#sceneLabel").textContent=room.name.toUpperCase();const root=$("#hotspots");root.innerHTML="";if(isCapturedSelf()){root.appendChild(hotspot("CAPTURED — WAIT FOR RESCUE",[28,38,44,22],()=>{},"captured-hotspot"));return;}room.neighbors.forEach((id,i)=>{const r=roomById(id);if(r)root.appendChild(hotspot(`Go: ${r.name}`,[3+(i%2)*78,42+Math.floor(i/2)*22,18,18],()=>moveTo(id),"exit"));});if(!shared[`visited:${room.id}`])setState(`visited:${room.id}`,{visited:true});const puzzleId=shared[`puzzle:${room.id}`]||null;if(puzzleId&&!shared[`solved:${room.id}`])root.appendChild(hotspot(`Puzzle: ${PUZZLES.find(p=>p.id===puzzleId)?.name||"Puzzle"}`,[35,20,30,22],()=>openPuzzle(puzzleId),"sprite-hotspot"));if(shared[`capturedIn:${room.id}`]&&players.some(p=>p.room===room.id&&shared[`captured:${p.user_id}`]))root.appendChild(hotspot("Free teammate",[62,64,27,22],()=>openRescue(room.id),"rescue-hotspot"));if(room.id===rooms[rooms.length-1]?.id)root.appendChild(hotspot("Leave building",[72,20,24,60],attemptExtraction,"sprite-hotspot"));root.appendChild(hotspot(hidden?"Leave hiding place":"Hide",[7,64,18,24],toggleHide,"hide-hotspot"));const evidenceKey=`evidence:${room.id}`;if(!shared[evidenceKey]&&evidenceCount()<requiredEvidence().length)root.appendChild(hotspot("Search",[38,52,24,18],()=>collectEvidence(room.id),"sprite-hotspot"));}
function hotspot(label,[x,y,w,h],fn,cls=""){const b=document.createElement("button");b.className=`hotspot ${cls}`;b.style.cssText=`left:${x}%;top:${y}%;width:${w}%;height:${h}%`;b.innerHTML=`<span>${esc(label)}</span>`;b.addEventListener("click",fn);return b;}

function renderMap(){const map=$("#minimap");if(!map)return;map.innerHTML="";map.style.cssText="position:relative;display:block;min-height:230px;";const svg=document.createElementNS("http://www.w3.org/2000/svg","svg");svg.setAttribute("viewBox","0 0 500 400");svg.style.cssText="position:absolute;inset:0;width:100%;height:100%;pointer-events:none;z-index:0";const visited=new Set(Object.keys(shared).filter(k=>k.startsWith("visited:")).map(k=>k.slice(8)));for(const r of rooms){for(const n of r.neighbors){const t=roomById(n);if(!t||r.id>t.id||(!visited.has(r.id)&&!visited.has(t.id)))continue;const line=document.createElementNS("http://www.w3.org/2000/svg","line");line.setAttribute("x1",r.x*100+50);line.setAttribute("y1",r.y*100+50);line.setAttribute("x2",t.x*100+50);line.setAttribute("y2",t.y*100+50);line.setAttribute("stroke","#607080");line.setAttribute("stroke-width","5");line.setAttribute("stroke-linecap","round");svg.appendChild(line);}}map.appendChild(svg);for(const r of rooms){const el=document.createElement("button"),seen=visited.has(r.id),current=r.id===currentRoom;el.className=`map-room ${seen?"visited":""} ${current?"current":""}`;el.style.cssText=`position:absolute;left:${r.x*20+1}%;top:${r.y*24+2}%;width:18%;height:20%;z-index:1;overflow:visible`;el.textContent=seen||current?r.name:"Unknown";if(activeModifiers().includes("dark")&&!seen&&!current)el.textContent="Unknown";const tags=r.tags||[];el.title=tags.length?tags.map(t=>`${t.label} — ${t.by}`).join("\n"):"Click to add a tag";el.onclick=()=>openRoomTagger(r.id);el.onmouseenter=()=>showRoomTags(el,tags);map.appendChild(el);}}
function showRoomTags(el,tags){if(!tags.length)return;let tip=el.querySelector(".map-tags-tooltip");if(!tip){tip=document.createElement("div");tip.className="map-tags-tooltip";el.appendChild(tip);}tip.innerHTML=tags.map(t=>`<div><b>${esc(t.label)}</b><small>${esc(t.by)}</small></div>`).join("");}
function openRoomTagger(roomId){const r=roomById(roomId);const tag=prompt(`Add a tag for ${r?.name||"room"}. Examples: CLEAR, GUARD, CLUE, DANGER, SEARCHED`);if(!tag)return;const label=tag.trim().slice(0,24);if(!label)return;const next=[...(r.tags||[]),{id:crypto.randomUUID(),label,by:window.currentProfile.nickname||window.currentProfile.username||"Detective"}];return setState("rooms",rooms.map(x=>x.id===roomId?{...x,tags:next}:x));}

function renderPlayers(){$("#onlineCount").textContent=`${players.length} online`;$("#playerList").innerHTML=players.map(p=>{const cap=shared[`captured:${p.user_id}`];const lives=(shared[`lives:${p.user_id}`]??(settings().lives*2))/2;return `<div class="player-row"><span>${esc(p.profiles?.nickname||"Detective")}${cap?' · CAPTURED':''}</span><small>${esc(roomById(p.room)?.name||p.room)} · ${lives} lives</small></div>`}).join("");}
function renderEvidenceCount(){$("#evidenceCounter").textContent=`Evidence ${evidenceCount()}/${requiredEvidence().length}`;}
function renderGameHud(){ensureGameHud();const locked=isCapturedSelf();["inventoryBtn","hintBtn","notesBtn","settingsBtn"].forEach(id=>$("#"+id)?.toggleAttribute("disabled",locked));const lives=((shared[`lives:${uid()}`]??(settings().lives*2))/2).toFixed(1).replace(/\.0$/,'');$("#nsdLives").textContent=`Lives ${lives}`;$("#nsdCaptured").classList.toggle("hidden",!locked);$("#chatForm")?.classList.toggle("disabled-chat",locked);$("#chatInput")?.toggleAttribute("disabled",locked);$("#chatForm button")?.toggleAttribute("disabled",locked);}
function ensureGameHud(){let hud=$("#nsdGameHud");if(!hud){hud=document.createElement("div");hud.id="nsdGameHud";hud.innerHTML=`<span id="nsdLives">Lives</span><span id="nsdTimer">Time</span><span id="nsdCaptured" class="hidden">CAPTURED</span>`;$(".game-topbar")?.appendChild(hud);}}
function startGameTimer(){clearInterval(gameTimer);const limit=getEffectiveTimeLimit();if(!gameStartedAt)gameStartedAt=shared["game:startedAt"]||Date.now();gameTimer=setInterval(()=>{const elapsed=Math.floor((Date.now()-gameStartedAt)/1000),left=Math.max(0,limit-elapsed),el=$("#nsdTimer");if(el)el.textContent=`${getPrefs().visibleTimer===false&&!getPrefs().speedRun?"":"Time "+left+"s"}`;if(checkRunDestination()){clearInterval(gameTimer);return;}if(left<=0){clearInterval(gameTimer);gameOver("time");}},500);}
function getEffectiveTimeLimit(){let n=Number(settings().timeLimit)||240;if(activeModifiers().includes("rush"))n=Math.floor(n*.8);if(owned("time_boost"))n+=60;return n;}
function owned(id){return(window.__shopOwned||[]).includes(id)||JSON.parse(localStorage.getItem(`nsd-shop-${uid()}`)||"[]").includes(id);}
function checkRunDestination(){const dest=getPrefs().speedRun?(getPrefs().runDestination||"finish"):"finish";if(dest==="rooms"&&rooms.length&&rooms.every(r=>shared[`visited:${r.id}`])){awardRun(true,"rooms");return true;}if(dest==="evidence"&&evidenceCount()>=requiredEvidence().length){awardRun(true,"evidence");return true;}return false;}
function gameOver(reason){if(shared["game:ended"])return;setState("game:ended",{reason,at:Date.now()});awardRun(false,reason);toast(reason==="time"?"Time limit reached. The team is out of time.":"The team ran out of lives.");}

function openPuzzle(id){if(isCapturedSelf())return;const p=PUZZLES.find(x=>x.id===id);if(!p)return;activePuzzle=p;const d=$("#puzzleDialog"),root=$("#puzzleContent");let body=`<div class="puzzle-grid"><div class="eyebrow">PUZZLE</div><h2>${esc(p.name)}</h2><p>${esc(p.prompt)}</p>`;if(["morse","keypad","sequence","anagram","symbols","frequency","directions","colors","math","pattern","terminal"].includes(p.type))body+=`<div class="code-input"><input id="puzzleAnswer" autocomplete="off" placeholder="Answer"><button id="puzzleSubmit" class="primary">Submit</button></div>`;else if(p.type==="lock")body+=`<div class="lockpick"><div class="lock-core"><div class="lock-target"></div><div id="lockLine" class="lock-line"></div></div></div><small>Use A/D and press Space when aligned.</small>`;else if(p.type==="switch")body+=`<div class="switches">${[1,2,3].map(i=>`<button class="secondary switch-btn" data-on="false">Switch ${i}</button>`).join("")}</div><button id="switchSubmit" class="primary">Confirm</button>`;else if(p.type==="memory")body+=`<div class="memory-grid">${Array.from({length:9},(_,i)=>`<button class="secondary memory-cell" data-i="${i}">${i+1}</button>`).join("")}</div>`;body+=`</div>`;root.innerHTML=body;d.showModal();if(p.type==="lock")setupLockPuzzle();else if(p.type==="switch")setupSwitchPuzzle();else if(p.type==="memory")setupMemoryPuzzle();else $("#puzzleSubmit")?.addEventListener("click",()=>solvePuzzle($("#puzzleAnswer").value));}
function solvePuzzle(answer){const p=activePuzzle;if(!p)return;const normalized=String(answer).trim().toUpperCase().replace(/\s+/g," ");if(normalized!==p.answer)return beep(100,.08,"sawtooth");completePuzzle(p.id);}
async function completePuzzle(id){const p=PUZZLES.find(x=>x.id===id);await setState(`solved:${currentRoom}`,{puzzle:id,by:uid(),at:Date.now()});await setState(`puzzle:${currentRoom}`,null);await supabase.rpc("increment_stat",{target_user:uid(),stat_name:"puzzles_solved",amount:1});$("#puzzleDialog").close();activePuzzle=null;toast(`${p?.name||"Puzzle"} solved.`);beep(880,.15,"triangle");}
function setupLockPuzzle(){let angle=0;const keys=new Set();const update=()=>{angle=clamp(angle+(keys.has("d")?2.3:0)-(keys.has("a")?2.3:0),-90,180);const l=$("#lockLine");if(l)l.style.transform=`rotate(${angle}deg)`;};const kd=e=>{const k=e.key.toLowerCase();if(k==="a"||k==="d")keys.add(k);if(e.code==="Space"){e.preventDefault();if(angle>=72&&angle<=88){cleanup();completePuzzle(activePuzzle.id);}else beep(130,.08,"sawtooth");}};const ku=e=>keys.delete(e.key.toLowerCase());const cleanup=()=>{clearInterval(timer);window.removeEventListener("keydown",kd);window.removeEventListener("keyup",ku)};const timer=setInterval(update,16);window.addEventListener("keydown",kd);window.addEventListener("keyup",ku);$("#puzzleDialog").addEventListener("close",cleanup,{once:true});}
function setupSwitchPuzzle(){document.querySelectorAll(".switch-btn").forEach(b=>b.onclick=()=>{b.dataset.on=b.dataset.on!=="true";b.textContent=`Switch ${b.dataset.on==="true"?"ON":"OFF"}`;});$("#switchSubmit").onclick=()=>{const on=[...document.querySelectorAll(".switch-btn")].filter(b=>b.dataset.on==="true").length;if(on===3)completePuzzle(activePuzzle.id);else beep(120,.08,"sawtooth");};}
function setupMemoryPuzzle(){const seq=shuffle([...Array(9).keys()]).slice(0,4);let pos=0;setTimeout(()=>seq.forEach((i,j)=>setTimeout(()=>document.querySelector(`.memory-cell[data-i="${i}"]`)?.classList.add("active-memory"),j*350)),200);setTimeout(()=>document.querySelectorAll(".memory-cell").forEach(b=>b.classList.remove("active-memory")),1800);document.querySelectorAll(".memory-cell").forEach(b=>b.onclick=()=>{if(Number(b.dataset.i)!==seq[pos])return beep(100,.08,"sawtooth");pos++;if(pos===seq.length)completePuzzle(activePuzzle.id);});}

async function collectEvidence(roomId){if(isCapturedSelf()||shared[`evidence:${roomId}`])return;const key=requiredEvidence()[evidenceCount()];await setState(`evidence:${roomId}`,{item:key,by:uid(),at:Date.now()});await setState(`evidence:${key}`,{room:roomId,by:uid(),at:Date.now()});await supabase.rpc("increment_stat",{target_user:uid(),stat_name:"clues_found",amount:1});toast(`Recovered ${key.toUpperCase()}.`);beep(720,.1);}
async function moveTo(roomId){if(isCapturedSelf())return toast("You are captured. Another detective must free you.");const room=roomById(currentRoom);if(!room?.neighbors.includes(roomId))return toast("That room is not connected.");currentRoom=roomId;hidden=false;await supabase.from("session_players").update({room:roomId,is_hidden:false,last_seen:new Date().toISOString()}).eq("session_id",session.id).eq("user_id",uid());await setState(`visited:${roomId}`,{visited:true});renderAll();maybeTriggerGuard();beep(240,.08,"triangle");}
async function toggleHide(){if(isCapturedSelf())return;hidden=!hidden;await supabase.from("session_players").update({is_hidden:hidden,last_seen:new Date().toISOString()}).eq("session_id",session.id).eq("user_id",uid());renderAll();beep(hidden?180:360,.12);}
function maybeTriggerGuard(){const s=settings();if(s.guards<=0||hidden||isCapturedSelf())return;const chance={easy:.12,normal:.2,hard:.32}[s.difficulty]||.2;if(Math.random()>chance)return;clearTimeout(guardTimer);guardTimer=setTimeout(()=>guardApproach(s),800+Math.random()*1800);}
function guardApproach(s){let seconds=clamp(Number(s.guardWarning)||5,2,10);$("#guardCountdown").textContent=seconds;$("#guardBanner").classList.remove("hidden");beep(90,.15,"square",.08);clearInterval(guardCountdownTimer);guardCountdownTimer=setInterval(()=>{seconds--;$("#guardCountdown").textContent=Math.max(0,seconds);if(seconds<=0){clearInterval(guardCountdownTimer);guardArrived(s);}},1000);}
async function guardArrived(){$("#guardBanner").classList.add("hidden");if(hidden){toast("The guard passed without finding you.");beep(300,.1);return;}await capturePlayer();}
async function capturePlayer(){if(isCapturedSelf())return;const halfLoss=activeModifiers().includes("fragile")?2:1,old=(shared[`lives:${uid()}`]??(settings().lives*2)),next=Math.max(0,old-halfLoss),info={room:currentRoom,until:Date.now()+(Number(settings().guardCapture)||45)*1000,halfLoss};await setState(`captured:${uid()}`,info);await setState(`lives:${uid()}`,next);await setState(`capturedIn:${currentRoom}`,{userId:uid(),room:currentRoom});hidden=false;renderAll();beep(70,.25,"sawtooth",.08);startCaptureTimer(info);if(next<=0)gameOver("lives");}
function startCaptureTimer(info){clearInterval(guardCountdownTimer);guardCountdownTimer=setInterval(async()=>{const left=Math.max(0,Math.ceil((info.until-Date.now())/1000));$("#guardCountdown").textContent=left;if(left<=0){clearInterval(guardCountdownTimer);await releaseCapture("timeout");}},500);}
async function releaseCapture(reason){if(!isCapturedSelf())return;await setState(`captured:${uid()}`,null);await supabase.from("session_players").update({is_hidden:false,last_seen:new Date().toISOString()}).eq("session_id",session.id).eq("user_id",uid());renderAll();toast(reason==="rescue"?"Your teammate freed you.":"The guard moved on. You are free.");}
function openRescue(roomId){if(isCapturedSelf())return;const target=players.find(p=>p.room===roomId&&shared[`captured:${p.user_id}`]);if(!target)return toast("Nobody is captured here.");activePuzzle={id:`rescue-${target.user_id}`,name:"Rescue Lock",type:"rescue",target:target.user_id};const d=$("#puzzleDialog");$("#puzzleContent").innerHTML=`<div class="puzzle-grid"><div class="eyebrow">RESCUE</div><h2>Free ${esc(target.profiles?.nickname||"teammate")}</h2><p>Solve the rescue lock: 12 + 6 × 2 = ?</p><div class="code-input"><input id="puzzleAnswer" placeholder="Answer"><button id="puzzleSubmit" class="primary">Unlock</button></div></div>`;d.showModal();$("#puzzleSubmit").onclick=async()=>{if($("#puzzleAnswer").value.trim()!=="24")return beep(100,.08,"sawtooth");await setState(`captured:${target.user_id}`,null);await setState(`rescued:${target.user_id}`,{by:uid(),at:Date.now()});d.close();toast("Teammate freed.");beep(880,.15,"triangle");};}

function renderMessages(messages){const root=$("#chatMessages");if(!root)return;root.innerHTML=messages.map(m=>`<div class="message"><b>${esc(m.profiles?.nickname||"Detective")}</b>${esc(m.body)}</div>`).join("");root.scrollTop=root.scrollHeight;renderGameHud();}
async function sendMessage(){if(isCapturedSelf())return toast("You cannot chat while captured.");const input=$("#chatInput"),body=input.value.trim();if(!body||!session)return;input.value="";const{error}=await supabase.from("messages").insert({session_id:session.id,user_id:uid(),body});if(error)toast(error.message);else beep(520,.05);}
async function attemptExtraction(){if(isCapturedSelf())return;const runDest=getPrefs().speedRun?(getPrefs().runDestination||"finish"):"finish";if(runDest==="rooms"||runDest==="evidence")return toast("Your speed-run destination is not the extraction yet.");const req=requiredEvidence();if(evidenceCount()<req.length)return toast(`You need all ${req.length} required evidence items.`);if(players.length&&!players.every(p=>!shared[`captured:${p.user_id}`]))return toast("Every detective must be free before extraction.");await setState(`extracted:${uid()}`,{at:Date.now()});toast("You made it outside. Wait for the rest of the team.");const fresh=await supabase.from("session_players").select("user_id").eq("session_id",session.id);const all=(fresh.data||[]).every(p=>shared[`extracted:${p.user_id}`]);if(all&&fresh.data?.length){await supabase.rpc("complete_game",{target_session:session.id});await awardRun(true,"finish");toast("Case closed. The whole team extracted.");}}
async function awardRun(success,destination){if(shared["run:awarded"])return;await setState("run:awarded",{at:Date.now()});const elapsed=Math.floor((Date.now()-(gameStartedAt||Date.now()))/1000);let coins=0;coins+=evidenceCount()*10;if(requiredEvidence().every(k=>shared[`evidence:${k}`]))coins+=50;if(rooms.length&&rooms.every(r=>shared[`visited:${r.id}`]))coins+=100;if(success)coins+=150;if(owned("clue_bonus"))coins=Math.round(coins*1.1);if(owned("explorer")&&rooms.length&&rooms.every(r=>shared[`visited:${r.id}`]))coins=Math.round(coins*1.2);if(owned("survivor")&&success)coins=Math.round(coins*1.15);coins=Math.round(coins*(1+modifierScore()/100));if(!success)coins=Math.floor(coins*.5);try{await supabase.rpc("award_coins",{amount:coins});await supabase.from("run_logs").insert({user_id:uid(),session_id:session?.id||null,settings:{...settings(),modifiers:activeModifiers(),speedRun:getPrefs().speedRun,visibleTimer:getPrefs().visibleTimer},destination,elapsed_seconds:elapsed,success,modifier_score:modifierScore(),coins_earned:coins});}catch(e){console.warn("Run reward logging unavailable",e);}toast(`Run recorded: +${coins} coins${success?"":" (50% failure payout)"}.`);}

function renderMainMenu(){ensureMainMenuButtons();}
function ensureMainMenuButtons(){const nav=$("#lobbyView .topbar nav");if(!nav)return;for(const[id,label,fn]of[["mainSettingsBtn","Settings",openMainSettings],["shopBtn","Shop",openShop],["runsBtn","Run log",openRunLog]]){if(!$("#"+id)){const b=document.createElement("button");b.id=id;b.className="ghost";b.textContent=label;b.onclick=fn;nav.insertBefore(b,$("#logoutBtn"));}}}
function openMainSettings(){const d=getOrCreateDialog("mainSettingsDialog","SETTINGS","<div id="mainSettingsForm" class="settings-form"></div><div class="modal-actions"><button id="mainSettingsReset" class="ghost">Reset</button><button id="mainSettingsSave" class="primary">Apply</button></div>");const p=getPrefs();$("#mainSettingsForm").innerHTML=`<label>Sound effects<select data-pref="sounds"><option value="true">On</option><option value="false">Off</option></select></label><label>Music<select data-pref="music"><option value="true">On</option><option value="false">Off</option></select></label><label>Graphics<select data-pref="graphics"><option value="high">High</option><option value="low">Low</option></select></label><label>Master volume <output>${Math.round(p.masterVolume*100)}%</output><input data-pref="masterVolume" type="range" min="0" max="1" step=".05" value="${p.masterVolume}"></label><hr><div class="eyebrow">PROFILE</div><label>Username <input id="profileUsername" value="${esc(window.currentProfile?.username||"")}" maxlength="24"></label><label>Nickname <input id="profileNickname" value="${esc(window.currentProfile?.nickname||"")}" maxlength="28"></label><label>New password <input id="profilePassword" type="password" minlength="8" placeholder="Leave blank to keep current"></label><button id="profileSave" class="secondary">Save profile</button><hr><div class="eyebrow">SPEED RUN</div><label><input id="speedRun" type="checkbox" ${p.speedRun?"checked":""}> Enable speed run</label><label>Visible timer<select id="visibleTimer"><option value="true">Visible</option><option value="false">Hidden</option></select></label><label>Run destination<select id="runDestination"><option value="rooms">Discover every room</option><option value="evidence">Find all evidence</option><option value="finish">Finish the game</option></select></label>`;$("#mainSettingsForm select[data-pref="sounds"]").value=String(p.sounds);$("#mainSettingsForm select[data-pref="music"]").value=String(p.music);$("#mainSettingsForm select[data-pref="graphics"]").value=p.graphics;$("#visibleTimer").value=String(p.visibleTimer);$("#runDestination").value=p.runDestination;$("#mainSettingsForm [data-pref="masterVolume"]").oninput=e=>e.target.parentElement.querySelector("output").textContent=`${Math.round(e.target.value*100)}%`;$("#mainSettingsSave").onclick=()=>{const q={...getPrefs(),sounds:$("#mainSettingsForm select[data-pref="sounds"]").value==="true",music:$("#mainSettingsForm select[data-pref="music"]").value==="true",graphics:$("#mainSettingsForm select[data-pref="graphics"]").value,masterVolume:Number($("#mainSettingsForm [data-pref="masterVolume"]").value),speedRun:$("#speedRun").checked,visibleTimer:$("#visibleTimer").value==="true",runDestination:$("#runDestination").value};savePrefs(q);if(q.music)startMusic();else stopMusic();d.close();};$("#mainSettingsReset").onclick=()=>{savePrefs(DEFAULT_SETTINGS);openMainSettings();};$("#profileSave").onclick=saveProfile;d.showModal();}
async function saveProfile(){const username=$("#profileUsername").value.trim().toLowerCase(),nickname=$("#profileNickname").value.trim(),password=$("#profilePassword").value;if(!/^[A-Za-z0-9_]{3,24}$/.test(username)||nickname.length<2)return toast("Enter a valid username and nickname.");if(password&&password.length<8)return toast("Password must be at least 8 characters.");if(username!==window.currentProfile.username){const{data:{session:authSession}}=await supabase.auth.getSession();if(!authSession)return toast("Your session expired. Log in again.");const response=await fetch(`${CONFIG.SUPABASE_URL}/functions/v1/change-username`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${authSession.access_token}`},body:JSON.stringify({username})});const result=await response.json().catch(()=>({}));if(!response.ok)return toast(result.error||"Username change is unavailable until the Supabase username function is deployed.");}const{error}=await supabase.from("profiles").update({username,nickname,updated_at:new Date().toISOString()}).eq("id",uid());if(error)return toast(error.message);if(password){const{error:pwError}=await supabase.auth.updateUser({password});if(pwError)return toast(pwError.message);}window.currentProfile.username=username;window.currentProfile.nickname=nickname;$("#profileLine").textContent=`${nickname} · @${username} · ${uid().slice(0,8)}`;toast("Profile updated.");}
function getOrCreateDialog(id,title,html){let d=$("#"+id);if(!d){d=document.createElement("dialog");d.id=id;d.className="modal";d.innerHTML=`<button class="modal-close" onclick="this.parentElement.close()">×</button><div class="eyebrow">${title}</div><h2>${title}</h2>${html}`;document.body.appendChild(d);}return d;}
async function openShop(){const d=getOrCreateDialog("shopDialog","SHOP",`<div id="shopList" class="inventory-list"></div>`);const[{data:stats},{data:items}]=await Promise.all([supabase.from("player_stats").select("coins").eq("user_id",uid()).single(),supabase.from("player_items").select("item_id").eq("user_id",uid())]);window.__shopOwned=(items||[]).map(x=>x.item_id);const coins=stats?.coins||0;$("#shopList").innerHTML=`<div class="evidence-item"><strong>Coins: ${coins}</strong><small>Earn coins by finding evidence, exploring, and finishing runs.</small></div>`+SHOP_ITEMS.map(i=>`<div class="evidence-item"><strong>${i.name} · ${i.price} coins</strong><small>${i.desc}</small><button class="secondary shop-buy" data-item="${i.id}" ${owned(i.id)?"disabled":""}>${owned(i.id)?"Owned":"Buy"}</button></div>`).join("");d.querySelectorAll(".shop-buy").forEach(b=>b.onclick=()=>buyItem(b.dataset.item));d.showModal();}
async function buyItem(id){const item=SHOP_ITEMS.find(x=>x.id===id);if(!item||owned(id))return;const{error}=await supabase.rpc("spend_coins",{amount:item.price});if(error)return toast(error.message);const{error:itemError}=await supabase.from("player_items").insert({user_id:uid(),item_id:id});if(itemError)return toast(itemError.message);window.__shopOwned=[...(window.__shopOwned||[]),id];toast(`Purchased ${item.name}.`);openShop();}
async function openRunLog(){const d=getOrCreateDialog("runLogDialog","RUN LOG",`<div id="runLogList" class="inventory-list"></div>`);const{data,error}=await supabase.from("run_logs").select("*").eq("user_id",uid()).order("created_at",{ascending:false}).limit(30);if(error)return toast(error.message);$("#runLogList").innerHTML=(data||[]).map(r=>`<div class="evidence-item"><strong>${r.success?"COMPLETED":"FAILED"} · ${esc(r.destination)}</strong><small>${r.elapsed_seconds}s · ${r.coins_earned} coins · modifier score ${r.modifier_score}<br>${esc(JSON.stringify(r.settings))}</small></div>`).join("")||'<div class="empty-state">No runs recorded yet.</div>';d.showModal();}
function openNotes(){const d=$("#notesDialog");$("#notesText").value=localStorage.getItem(NOTES_KEY())||"";d.showModal();$("#notesText").focus();}
function saveNotes(){localStorage.setItem(NOTES_KEY(),$("#notesText").value);$("#notesDialog").close();toast("Notes saved locally.");}
function setupButtons(){$("#createGameBtn")?.addEventListener("click",createGame);$("#joinForm")?.addEventListener("submit",e=>{e.preventDefault();joinByCode($("#joinCode").value)});$("#startGameBtn")?.addEventListener("click",startGame);$("#copyCodeBtn")?.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(session.code)}catch{}toast("Team code copied.");});$("#leaveLobbyBtn")?.addEventListener("click",leaveSession);$("#leaveGameBtn")?.addEventListener("click",leaveSession);$("#chatForm")?.addEventListener("submit",e=>{e.preventDefault();sendMessage();});$("#inventoryBtn")?.addEventListener("click",openInventory);$("#hintBtn")?.addEventListener("click",()=>toast(currentObjective()));$("#notesBtn")?.addEventListener("click",openNotes);$("#saveNotesBtn")?.addEventListener("click",saveNotes);$("#clearNotesBtn")?.addEventListener("click",()=>$("#notesText").value="");$("#closeNotesBtn")?.addEventListener("click",()=>$("#notesDialog").close());$("#teamLobbySettingsBtn")?.addEventListener("click",openMainSettings);$("#closePuzzleBtn")?.addEventListener("click",()=>$("#puzzleDialog").close());$("#closeInventoryBtn")?.addEventListener("click",()=>$("#inventoryDialog").close());}
function currentObjective(){if(evidenceCount()<requiredEvidence().length)return`Objective: recover ${requiredEvidence().length-evidenceCount()} more evidence.`;if(rooms.some(r=>!shared[`visited:${r.id}`]))return"Objective: discover every room.";return"Objective: extract the entire team.";}
function openInventory(){const root=$("#inventoryList");root.innerHTML=requiredEvidence().filter(k=>shared[`evidence:${k}`]).map(k=>`<div class="evidence-item"><strong>${esc(k.toUpperCase())}</strong><small>Recovered by the team.</small></div>`).join("")||'<div class="empty-state">No evidence recovered yet.</div>';$("#inventoryDialog").showModal();}
async function leaveSession(){clearTimeout(guardTimer);clearInterval(guardCountdownTimer);clearInterval(gameTimer);stopMusic();if(channel)supabase.removeChannel(channel);channel=null;if(session&&window.currentProfile)await supabase.from("session_players").delete().eq("session_id",session.id).eq("user_id",uid());session=null;sessionPlayer=null;players=[];shared={};rooms=[];currentRoom=null;lobbyView();}
window.addEventListener("detective:signed-in",()=>{setupButtons();applyPrefs();renderMainMenu();});
if($("#puzzleDialog"))$("#puzzleDialog").addEventListener("close",()=>{activePuzzle=null;});
